#!/usr/bin/env node
/**
 * Reads strings/ui.yaml and writes src/generated/ui_i18n_gen.{h,c}
 */
'use strict';

const fs = require('fs');
const path = require('path');
const yaml = require('yaml');

const ROOT = path.join(__dirname, '..');
const YAML_PATH = path.join(ROOT, 'strings', 'ui.yaml');
const OUT_DIR = path.join(ROOT, 'src', 'generated');
const HDR = path.join(OUT_DIR, 'ui_i18n_gen.h');
const SRC = path.join(OUT_DIR, 'ui_i18n_gen.c');

/** All LANG_* ids that may be selected at runtime */
const LANG_IDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
/** Emit one struct per id here; other langs alias in ui_locale_for_lang (saves flash on aplite) */
const UNIQUE_STRUCT_IDS = [1, 2, 3, 4, 5, 6, 7, 9, 10];

const ORDINAL_COUNT = 31;

function structIdForLang(lid) {
  if (lid === 8) return 7;
  if (lid === 11) return 2;
  return lid;
}

function cEscape(s) {
  if (s == null) return '""';
  return (
    '"' +
    String(s)
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\r/g, '\\r')
      .replace(/\n/g, '\\n') +
    '"'
  );
}

function flattenLocale(entry) {
  if (entry && typeof entry === 'object' && entry['<<']) {
    const merged = { ...entry['<<'], ...entry };
    delete merged['<<'];
    return merged;
  }
  return entry;
}

function main() {
  const raw = fs.readFileSync(YAML_PATH, 'utf8');
  const doc = yaml.parse(raw);
  if (!doc || !doc.locales) {
    throw new Error('Invalid ui.yaml: missing locales');
  }

  const header = `/* Generated by scripts/codegen-ui.js — do not edit. */
#pragma once
#include <stdint.h>
#include <stddef.h>

#define UI_ORDINAL_COUNT ${ORDINAL_COUNT}

typedef struct UiLocale {
  const char *bat_low;
  /** If non-empty, prepended to each ordinal (saves flash vs repeating per day). */
  const char *day_prefix;
  const char *ordinals[UI_ORDINAL_COUNT];
} UiLocale;

const UiLocale *ui_locale_for_lang(uint8_t lang);
/** Ordinal word/phrase only (no day_prefix). */
const char *ui_ordinal_for_lang_day(uint8_t lang, int day);
const char *ui_bat_low_for_lang(uint8_t lang);
void ui_format_day_of_month(uint8_t lang, int day, char *buf, size_t len);
`;

  const inits = [];
  for (const sid of UNIQUE_STRUCT_IDS) {
    const L = flattenLocale(doc.locales[String(sid)]);
    if (!L) {
      throw new Error(`Missing locale ${sid} in ui.yaml`);
    }
    if (L.bat_low == null || L.bat_low === '') {
      throw new Error(`Locale ${sid}: bat_low required`);
    }
    const ord = L.ordinals;
    if (!Array.isArray(ord) || ord.length !== ORDINAL_COUNT) {
      throw new Error(
        `Locale ${sid}: ordinals must be a list of exactly ${ORDINAL_COUNT} strings (got ${ord ? ord.length : 'missing'})`
      );
    }
    const dp = L.day_prefix;
    const dpField =
      dp == null || dp === ''
        ? '  .day_prefix = NULL,'
        : `  .day_prefix = ${cEscape(dp)},`;
    const ordLines = ord.map((s) => `    ${cEscape(s)}`).join(',\n');
    inits.push(
      `static const UiLocale UL_${sid} = {
  .bat_low = ${cEscape(L.bat_low)},
${dpField}
  .ordinals = {
${ordLines}
  }
};`
    );
  }

  const localeSwitch = LANG_IDS.map(
    (lid) => `    case ${lid}: return &UL_${structIdForLang(lid)};`
  ).join('\n');

  const source = `/* Generated by scripts/codegen-ui.js — do not edit. */
#include "ui_i18n_gen.h"
#include <stdio.h>

${inits.join('\n\n')}

const UiLocale *ui_locale_for_lang(uint8_t lang) {
  switch (lang) {
${localeSwitch}
    default:
      return &UL_2;
  }
}

const char *ui_ordinal_for_lang_day(uint8_t lang, int day) {
  const UiLocale *L = ui_locale_for_lang(lang);
  if (day < 1 || day > UI_ORDINAL_COUNT) {
    return "";
  }
  const char *s = L->ordinals[day - 1];
  return s ? s : "";
}

const char *ui_bat_low_for_lang(uint8_t lang) {
  const UiLocale *L = ui_locale_for_lang(lang);
  return L->bat_low ? L->bat_low : "";
}

void ui_format_day_of_month(uint8_t lang, int day, char *buf, size_t len) {
  const UiLocale *L = ui_locale_for_lang(lang);
  if (!buf || len == 0) {
    return;
  }
  if (day < 1 || day > UI_ORDINAL_COUNT) {
    buf[0] = '\\0';
    return;
  }
  const char *s = L->ordinals[day - 1];
  if (!s) {
    s = "";
  }
  if (L->day_prefix && L->day_prefix[0]) {
    snprintf(buf, len, "%s%s", L->day_prefix, s);
  } else {
    snprintf(buf, len, "%s", s);
  }
}
`;

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(HDR, header);
  fs.writeFileSync(SRC, source);
  console.error('Wrote', HDR, SRC);
}

main();
